### ISSUE TITLE
No Type Definitions

### ISSUE THREAD

**Issue by robbyemmert** [vweevers/node-docker-machine#16]
Adding type definitions would add huge value. Several major IDEs are basing intellisense and code linting on Typescript definition files, even for non-typescript JS files. This makes libraries a breeze to use and can help increase adoption.

I may be writing some limited types for our own use. If they would help, or you need some more TS insight, let me know.

Thanks,

**Comment by vweevers** [comment]
PR is welcome to add typings, but note I'm not gonna maintain them, so you might want to add them to DT instead.
