### ISSUE TITLE
Cannot remove machine

### ISSUE THREAD

**Issue by stephan227** [vweevers/node-docker-machine#30]
How do I remove a machine?
I was reviewing the documentation and the code and I could not find the remove option.

I tried using the Machine.command but its not returning anything or working:
```
  Machine.command([`rm`, `${machineName}`], (err, result) => {
    console.log('error', err)
    console.log('result', result)
  })
```

Is there a way to remove a docker-machine?

**Comment by vweevers** [comment]
> I was reviewing the documentation and the code and I could not find the remove option

Correct, we don't currently have a method for it. A PR is welcome.

> I tried using the Machine.command but its not returning anything or working

Not sure why. Maybe you need a flag like `-y` to skip user confirmation.

**Comment by stephan227** [comment]
Thank you, I did not add the `-` to the `y` flag.  

I added the flag and it worked:
`
Machine.command(['rm', machineName, '-y'], (err, result) => {
`

**Comment by vweevers** [comment]
Cool. Closing for now. If anyone wants to add a `Machine.remove()` method, a PR is welcome.
