### ISSUE TITLE
plans for machine create?

### ISSUE THREAD

**Issue by jshimko** [vweevers/node-docker-machine#4]
I just stumbled on this while searching to see if a module existed before writing my own.  Great stuff so far!

Any plans to implement the `docker-machine create` API?  Creating/deleting machines with any of the supported drivers was one of the biggest parts I needed to build this for, but I'll surely end up needing the full API eventually.  Before I go off and duplicate effort, I figured it was worth checking in to see what your plans are.  I'd be happy just contribute here instead if you plan to build out the full API.

If you're open to collaboration, let's talk!

**Comment by jshimko** [comment]
I should also say... if this project already does what you need, please don't hesitate to tell me you're not interested.  I'm happy to just build my own module (since that was the original plan anyway).  I just wanted to offer in case you already had plans to expand the API.

**Comment by vweevers** [comment]
While this module does what I need, I'm open to new features. That comes with claiming the `docker-machine` npm name. Makes perfect sense to add `create` here, and any other missing commands. So PR's are very much welcome.

**Comment by vweevers** [comment]
Available in 3.0.0.
